### ISSUE TITLE
Il link al repo di Karbb è sbagliato

### ISSUE THREAD

**Issue by davcri** [GameLoop-it/cs50_course_materials#3]
Ho cannato un copia incolla! 

Il link corretto è questo: https://github.com/Karbb/pong-CS50

**Comment by winterismute** [comment]
In pratica @encelo ha cliccato il bottone l'unica volta che non doveva!

**Comment by winterismute** [comment]
Direi, submit di nuova pull request? Puoi farla anche da web.
